//
// This file was generated by the JPA Modeler
//
package hu.horvathzoltan.entity;

import java.io.Serializable;
import hu.horvathzoltan.type.MachineType;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

@Entity
public class Machine implements Serializable {

    @Id
    @GeneratedValue
    private Long id;

    @Basic
    @NotNull
    @Size(min = 1)
    private String name;

    @Basic
    @Size(min = 1)
    private int machineSize;

    @Basic
    @Size(min = 1)
    private int ticketPrice;

    @Basic
    @Size(min = 1)
    private int capacity;

    @Basic
    @Enumerated(EnumType.STRING)
    private MachineType type;

    @Basic
    @Size(min = 1)
    private int ageLimit;
    
    private int price;

    @ManyToOne(targetEntity = Park.class)
    private Park park;

    @OneToMany(targetEntity = Visitor.class, mappedBy = "machine")
    private List<Visitor> visitors;

    public Machine() {
        //No-arg constructor
    }

    public int getPrice() {
        return price;
    }

    public void setPrice(int price) {
        this.price = price;
    }
    

    public Machine(String name, int machineSize, int ticketPrice, int capacity, MachineType type, int ageLimit, int price, Park park) {
        this.name = name;
        this.machineSize = machineSize;
        this.ticketPrice = ticketPrice;
        this.capacity = capacity;
        this.type = type;
        this.ageLimit = ageLimit;
        this.price = price;
        this.park = park;
    }

    
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getMachineSize() {
        return this.machineSize;
    }

    public void setMachineSize(int machineSize) {
        this.machineSize = machineSize;
    }

    public int getTicketPrice() {
        return this.ticketPrice;
    }

    public void setTicketPrice(int ticketPrice) {
        this.ticketPrice = ticketPrice;
    }

    public int getCapacity() {
        return this.capacity;
    }

    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }

    public MachineType getType() {
        return this.type;
    }

    public void setType(MachineType type) {
        this.type = type;
    }

    public int getAgeLimit() {
        return this.ageLimit;
    }

    public void setAgeLimit(int ageLimit) {
        this.ageLimit = ageLimit;
    }

    public Park getPark() {
        return this.park;
    }

    public void setPark(Park park) {
        this.park = park;
    }

    public List<Visitor> getVisitors() {
        return this.visitors;
    }

    public void setVisitors(List<Visitor> visitors) {
        this.visitors = visitors;
    }
    public void addVisitor(Visitor visitor){
        visitors.add(visitor);
    }
}
