//
// This file was generated by the JPA Modeler
//
package hu.horvathzoltan.entity;

import java.io.Serializable;
import hu.horvathzoltan.state.VisitorState;
import java.util.Calendar;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

@Entity
public class Visitor implements Serializable {

    @Id
    @GeneratedValue
    private Long id;

    @NotNull
    @Size(min = 1)
    private String name;

    @Basic
    private int money;

    @Temporal(TemporalType.TIMESTAMP)
    @Basic
    private Calendar entryDate;

    @Basic
    private int age;

    @Basic
    private boolean active;

    @Basic
    @Enumerated(EnumType.STRING)
    private VisitorState state;

    @ManyToOne(targetEntity = Machine.class)
    private Machine machine;

    @ManyToOne(targetEntity = Park.class)
    private Park park;

    public Visitor() {
        this.active = true;
    }

    public Visitor(String name, int money, int age, boolean active, VisitorState state) {
        this.name = name;
        this.money = money;
        this.age = age;
        this.active = active;
        this.state = state;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getMoney() {
        return this.money;
    }

    public void setMoney(int money) {
        this.money = money;
    }

    public Calendar getEntryDate() {
        return this.entryDate;
    }

    public void setEntryDate(Calendar entryDate) {
        this.entryDate = entryDate;
    }

    public int getAge() {
        return this.age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public VisitorState getState() {
        return this.state;
    }

    public void setState(VisitorState state) {
        this.state = state;
    }

    public Machine getMachine() {
        return this.machine;
    }

    public void setMachine(Machine machine) {
        this.machine = machine;
    }

    public Park getPark() {
        return this.park;
    }

    public void setPark(Park park) {
        this.park = park;
    }
}
